version: "3.9"

services:
  postgresdb:
    image: "postgres"
    container_name: 'postgres-local'
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
      POSTGRES_DB: nest-jwt
    volumes:
      - data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: 'mongo-local'
    environment:
      - MONOG_INITDB_DATABASE=nest_main
      - MONOG_INITDB_ROOT_USERNAME=docker
      - MONOG_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ~/mongodb:/data/db
    ports:
      - '27018:27017'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  data:
