version: "3.9"

services:
  db:
    image: "postgres"
    container_name: 'postgres-local'
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: 'mongo-local'
    environment:
      - MONOG_INITDB_DATABASE=nest_main
      - MONOG_INITDB_ROOT_USERNAME=docker
      - MONOG_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ~/mongodb:/data/db
    ports:
      - '27018:27017'
volumes:
  data:
